# Generated by Django 4.1 on 2023-04-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Account",
        ),
    ]
