# Generated by Django 4.1 on 2023-04-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_alter_account_groups_alter_account_user_permissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="currency_symbol",
            new_name="currency",
        ),
    ]
