# Generated by Django 4.1 on 2023-04-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_rename_currency_symbol_account_currency"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[],
        ),
    ]
