# Generated by Django 4.1 on 2023-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "symbol",
                    models.CharField(
                        max_length=3, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("country", models.CharField(max_length=30, unique=True)),
                ("rate", models.FloatField()),
            ],
        ),
    ]
