# Generated by Django 4.1 on 2023-04-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0002_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="Currency",
                to="payapp.currency",
            ),
        ),
    ]
