# Generated by Django 4.1 on 2023-04-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0003_alter_transaction_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="receiver",
            new_name="recipient",
        ),
    ]
