# Generated by Django 4.1 on 2023-04-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0003_transaction_time_stamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="currency",
        ),
    ]
