# Generated by Django 4.1 on 2023-04-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0004_remove_transaction_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="time_stamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
