# Generated by Django 4.1 on 2023-04-09 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0004_rename_receiver_transaction_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(
                verbose_name=django.core.validators.MinValueValidator(0.0)
            ),
        ),
    ]
