# Generated by Django 4.1 on 2023-04-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0005_alter_transaction_time_stamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="time_stamp",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
