# Generated by Django 4.1 on 2023-04-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0006_alter_transaction_time_stamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_executed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_request",
            field=models.BooleanField(default=False),
        ),
    ]
